name: stylegan2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - backcall=0.2.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.5
  - conda=4.10.0
  - conda-package-handling=1.7.3
  - cryptography=3.4.7
  - decorator=5.0.6
  - icu=67.1
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - krb5=1.18.2
  - ld_impl_linux-64=2.33.1
  - libarchive=3.4.2
  - libcurl=7.71.1
  - libedit=3.1.20210216
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libiconv=1.16
  - libsodium=1.0.18
  - libsolv=0.7.16
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - mamba=0.7.3
  - ncurses=6.2
  - openssl=1.1.1k
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.0.1
  - prompt-toolkit=3.0.17
  - ptyprocess=0.7.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pygments=2.8.1
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.6.13
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pyzmq=20.0.0
  - readline=8.1
  - reproc=14.2.1
  - reproc-cpp=14.2.1
  - ruamel_yaml=0.15.100
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.60.0
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.12.0
    - astor==0.8.1
    - attrs==20.3.0
    - cached-property==1.5.2
    - chardet==3.0.4
    - comet-ml==3.8.1
    - configobj==5.0.6
    - dulwich==0.20.21
    - everett==1.0.3
    - gast==0.4.0
    - google-pasta==0.2.0
    - grpcio==1.37.0
    - h5py==3.1.0
    - idna==2.8
    - importlib-metadata==3.10.0
    - joblib==1.0.1
    - jsonschema==3.2.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - numpy==1.19.5
    - nvidia-ml-py3==7.352.0
    - pillow==6.2.1
    - protobuf==3.15.8
    - pyrsistent==0.17.3
    - python-dotenv==0.17.0
    - requests==2.22.0
    - requests-toolbelt==0.9.1
    - scipy==1.3.3
    - tensorboard==1.14.0
    - tensorflow-estimator==1.14.0
    - tensorflow-gpu==1.14.0
    - termcolor==1.1.0
    - typing-extensions==3.7.4.3
    - urllib3==1.25.11
    - websocket-client==0.58.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - wurlitzer==2.1.0
    - zipp==3.4.1

