name: ada-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.1.0
  - absl-py=0.7.1
  - astor=0.7.1
  - attrs=20.3.0
  - backcall=0.1.0
  - bleach=3.3.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2019.6.16
  - certifi=2019.6.16
  - cffi=1.14.4
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.6.0
  - conda=4.9.2
  - conda-package-handling=1.7.2
  - cryptography=2.8
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - cupti=10.0.130
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.3.1
  - dask-jobqueue=0.7.2
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.7.1
  - distributed=2021.3.1
  - entrypoints=0.3
  - expat=2.2.10
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - freetype=2.10.0
  - fsspec=0.8.7
  - gast=0.2.2
  - gettext=0.19.8.1
  - git=2.23.0
  - glib=2.58.3
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-pasta=0.1.7
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - h5py=2.9.0
  - hdf5=1.10.5
  - heapdict=1.0.1
  - icu=64.2
  - idna=2.8
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.2
  - importlib-metadata=3.7.3
  - importlib_metadata=3.7.3
  - ipykernel=5.1.2
  - ipython=7.7.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.14.1
  - jinja2=2.11.3
  - joblib=0.13.2
  - jpeg=9c
  - jsonschema=3.2.0
  - jupyterlab_widgets=1.0.0
  - keras-applications=1.0.7
  - keras-preprocessing=1.0.9
  - kiwisolver=1.1.0
  - krb5=1.17.1
  - lame=3.100
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.69.1
  - libedit=3.1.20181209
  - libevent=2.1.10
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.6
  - libpng=1.6.37
  - libprotobuf=3.9.1
  - libsodium=1.0.17
  - libsolv=0.7.16
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - locket=0.2.1
  - lz4-c=1.8.3
  - mamba=0.1.2
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mistune=0.8.4
  - msgpack-python=1.0.2
  - nbformat=5.1.2
  - ncurses=6.1
  - nettle=3.6
  - numpy=1.17.0
  - nvcc_linux-64=10.1
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1j
  - packaging=20.9
  - pandoc=2.12
  - parso=0.5.1
  - partd=1.1.0
  - pcre=8.44
  - perl=5.26.2
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.2.1
  - pip=19.2.2
  - prometheus_client=0.9.0
  - prompt_toolkit=2.0.9
  - psutil=5.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pygments=2.4.2
  - pyopenssl=20.0.1
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - python-dotenv=0.15.0
  - python_abi=3.7
  - pytz=2019.2
  - pyzmq=18.0.2
  - qt=5.9.7
  - readline=8.0
  - requests=2.22.0
  - ruamel_yaml=0.15.87
  - scikit-learn=0.21.3
  - scikit-plot=0.3.7
  - scipy=1.3.3
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sortedcontainers=2.3.0
  - sqlite=3.29.0
  - submitit=1.2.1
  - tblib=1.7.0
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - tensorflow-gpu=1.14.0
  - termcolor=1.1.0
  - testpath=0.4.4
  - tk=8.6.9
  - tmux=3.1
  - toolz=0.11.1
  - traitlets=4.3.2
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - wcwidth=0.1.7
  - werkzeug=0.15.5
  - wheel=0.33.4
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - x264=1!152.20180806
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - yaml=0.2.5
  - zeromq=4.3.2
  - zict=2.0.0
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - aiohttp==3.7.4.post0
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - async-timeout==3.0.1
    - beautifulsoup4==4.9.3
    - blessings==1.7
    - bounded-pool-executor==0.0.3
    - cachetools==4.2.1
    - colorama==0.4.4
    - colorful==0.5.4
    - comet-ml==3.8.1
    - configobj==5.0.6
    - dill==0.3.3
    - dulwich==0.20.21
    - everett==1.0.3
    - filelock==3.0.12
    - future==0.18.2
    - google==3.0.0
    - google-api-core==1.26.1
    - google-auth==1.28.0
    - googleapis-common-protos==1.53.0
    - gpustat==0.6.0
    - grpcio==1.36.1
    - hiredis==1.1.0
    - importlib-resources==5.1.2
    - ipyplot==1.1.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - kaggle==1.5.12
    - markdown2==2.4.0
    - multidict==5.1.0
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nest-asyncio==1.5.1
    - notebook==6.2.0
    - nvidia-ml-py3==7.352.0
    - opencensus==0.7.12
    - opencensus-context==0.1.2
    - pandas==1.2.3
    - pandocfilters==1.4.3
    - promise==2.3
    - protobuf==3.15.8
    - py-spy==0.3.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygifsicle==1.0.2
    - pyrsistent==0.17.3
    - python-slugify==4.0.1
    - pyyaml==5.4.1
    - redis==3.4.1
    - requests-toolbelt==0.9.1
    - rsa==4.7.2
    - send2trash==1.5.0
    - shortuuid==1.0.1
    - soupsieve==2.2
    - tabulate==0.8.9
    - tensorflow-datasets==4.2.0
    - tensorflow-metadata==0.30.0
    - terminado==0.9.3
    - text-unidecode==1.3
    - tornado==6.0.3
    - tqdm==4.59.0
    - webencodings==0.5.1
    - websocket-client==0.58.0
    - wurlitzer==2.1.0
    - yarl==1.6.3

